// ====== Tipos base ======
type Option<T extends string> = { value: T; label: string }

// #regionAnexo 3
export type EtniaValue =
  | "MAYA"
  | "XINCA"
  | "GARIFUNA"
  | "LADINOS"
  | "EXTRANJERO"
  | "OTRA"
type EtniaOption = { value: EtniaValue; label: string }

export const ETNIA_OPTIONS: EtniaOption[] = [
  { value: "MAYA", label: "Maya" },
  { value: "XINCA", label: "Xinca" },
  { value: "GARIFUNA", label: "Garífuna" },
  { value: "LADINOS", label: "Ladinos" },
  { value: "EXTRANJERO", label: "Extranjero" },
  { value: "OTRA", label: "Otra" },
]
// #endregion Anexo 3

// =======================
// #region Anexo 4 – Entidad a la que pertenece
// =======================
export type EntidadValue =
  | "CONTRALORÍA GENERAL DE CUENTAS"
  | "SOCIEDAD CIVIL"
  | "SECTOR FIDEICOMISOS"
  | "SECTOR DEFENSA, SEGURIDAD Y JUSTICIA"
  | "SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL"
  | "SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES"
  | "SECTOR GOBIERNOS LOCALES Y CONSEJOS DE DESARROLLO"
  | "SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES"
  | "SECTOR ORGANISMOS E INSTITUCIONES DE APOYO"
  | "SECTOR SALUD Y SEGURIDAD SOCIAL"

export const ENTIDAD_OPTIONS: Option<EntidadValue>[] = [
  {
    value: "CONTRALORÍA GENERAL DE CUENTAS",
    label: "CONTRALORÍA GENERAL DE CUENTAS",
  },
  { value: "SOCIEDAD CIVIL", label: "SOCIEDAD CIVIL" },
  { value: "SECTOR FIDEICOMISOS", label: "SECTOR FIDEICOMISOS" },
  {
    value: "SECTOR DEFENSA, SEGURIDAD Y JUSTICIA",
    label: "SECTOR DEFENSA, SEGURIDAD Y JUSTICIA",
  },
  {
    value: "SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL",
    label: "SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL",
  },
  {
    value: "SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES",
    label: "SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES",
  },
  {
    value: "SECTOR GOBIERNOS LOCALES Y CONSEJOS DE DESARROLLO",
    label: "SECTOR GOBIERNOS LOCALES Y CONSEJOS DE DESARROLLO",
  },
  {
    value: "SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES",
    label: "SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES",
  },
  {
    value: "SECTOR ORGANISMOS E INSTITUCIONES DE APOYO",
    label: "SECTOR ORGANISMOS E INSTITUCIONES DE APOYO",
  },
  {
    value: "SECTOR SALUD Y SEGURIDAD SOCIAL",
    label: "SECTOR SALUD Y SEGURIDAD SOCIAL",
  },
]

// =======================
// #region Anexo 5 – Institución a la que pertenece
// =======================
export type InstitucionValue =
  | "NO APLICA"
  | "ACADEMIA DE LENGUAS MAYAS DE GUATEMALA"
  | "AGENCIA NACIONAL DE ALIANZA PARA EL DESARROLLO DE INFRAESTRUCTURA ECONÓMICA"
  | "BENEMÉRITO CUERPO VOLUNTARIO DE BOMBEROS DE GUATEMALA"
  | "COMISIÓN NACIONAL DE ENERGÍA ELÉCTRICA"
  | "COMITÉ OLÍMPICO GUATEMALTECO"
  | "CONGRESO DE LA REPÚBLICA DE GUATEMALA"
  | "CONSEJO NACIONAL DE ADOPCIONES"
  | "CONSEJO NACIONAL PARA LA ATENCIÓN DE LAS PERSONAS CON DISCAPACIDAD"
  | "CONTRALORÍA GENERAL DE CUENTAS"
  | "COORDINADORA NACIONAL PARA LA REDUCCIÓN DE DESASTRES"
  | "CORTE DE CONSTITUCIONALIDAD"
  | "EMPRESA MUNICIPAL DE AGUA"
  | "EMPRESA PORTUARIA NACIONAL SANTO TOMÁS DE CASTILLA"
  | "ESCUELA NACIONAL CENTRAL DE AGRICULTURA"
  | "FEDERACIÓN NACIONAL DE AJEDREZ DE GUATEMALA"
  | "INSTITUTO DE LA DEFENSA PÚBLICA PENAL"
  | "INSTITUTO GUATEMALTECO DE TURISMO"
  | "INSTITUTO NACIONAL DE ADMINISTRACIÓN PÚBLICA"
  | "INSTITUTO NACIONAL DE BOSQUES"
  | "INSTITUTO TÉCNICO DE CAPACITACIÓN Y PRODUCTIVIDAD"
  | "MANCOMUNIDAD DE MUNICIPIOS DEL CONO SUR JUTIAPA"
  | "MINISTERIO DE SALUD PÚBLICA Y ASISTENCIA SOCIAL"
  | "MINISTERIO DE EDUCACIÓN"
  | "MINISTERIO DE GOBERNACIÓN"
  | "MUNICIPALIDAD DE GUATEMALA"
  | "PROCURADURÍA DE LOS DERECHOS HUMANOS"
  | "REGISTRO GENERAL DE LA PROPIEDAD"
  | "REGISTRO NACIONAL DE LAS PERSONAS"
  | "SUPERINTENDENCIA DE ADMINISTRACIÓN TRIBUTARIA"
  | "TRIBUNAL SUPREMO ELECTORAL"
  | "UNIVERSIDAD DE SAN CARLOS DE GUATEMALA"
  | "INSTITUTO GUATEMALTECO DE SEGURIDAD SOCIAL"

export const INSTITUCION_OPTIONS: Option<InstitucionValue>[] = [
  { value: "NO APLICA", label: "NO APLICA" },
  {
    value: "ACADEMIA DE LENGUAS MAYAS DE GUATEMALA",
    label: "ACADEMIA DE LENGUAS MAYAS DE GUATEMALA",
  },
  {
    value:
      "AGENCIA NACIONAL DE ALIANZA PARA EL DESARROLLO DE INFRAESTRUCTURA ECONÓMICA",
    label:
      "AGENCIA NACIONAL DE ALIANZA PARA EL DESARROLLO DE INFRAESTRUCTURA ECONÓMICA",
  },
  {
    value: "BENEMÉRITO CUERPO VOLUNTARIO DE BOMBEROS DE GUATEMALA",
    label: "BENEMÉRITO CUERPO VOLUNTARIO DE BOMBEROS DE GUATEMALA",
  },
  {
    value: "COMISIÓN NACIONAL DE ENERGÍA ELÉCTRICA",
    label: "COMISIÓN NACIONAL DE ENERGÍA ELÉCTRICA",
  },
  {
    value: "COMITÉ OLÍMPICO GUATEMALTECO",
    label: "COMITÉ OLÍMPICO GUATEMALTECO",
  },
  {
    value: "CONGRESO DE LA REPÚBLICA DE GUATEMALA",
    label: "CONGRESO DE LA REPÚBLICA DE GUATEMALA",
  },
  {
    value: "CONSEJO NACIONAL DE ADOPCIONES",
    label: "CONSEJO NACIONAL DE ADOPCIONES",
  },
  {
    value: "CONSEJO NACIONAL PARA LA ATENCIÓN DE LAS PERSONAS CON DISCAPACIDAD",
    label: "CONSEJO NACIONAL PARA LA ATENCIÓN DE LAS PERSONAS CON DISCAPACIDAD",
  },
  {
    value: "CONTRALORÍA GENERAL DE CUENTAS",
    label: "CONTRALORÍA GENERAL DE CUENTAS",
  },
  {
    value: "COORDINADORA NACIONAL PARA LA REDUCCIÓN DE DESASTRES",
    label: "COORDINADORA NACIONAL PARA LA REDUCCIÓN DE DESASTRES",
  },
  {
    value: "CORTE DE CONSTITUCIONALIDAD",
    label: "CORTE DE CONSTITUCIONALIDAD",
  },
  { value: "EMPRESA MUNICIPAL DE AGUA", label: "EMPRESA MUNICIPAL DE AGUA" },
  {
    value: "EMPRESA PORTUARIA NACIONAL SANTO TOMÁS DE CASTILLA",
    label: "EMPRESA PORTUARIA NACIONAL SANTO TOMÁS DE CASTILLA",
  },
  {
    value: "ESCUELA NACIONAL CENTRAL DE AGRICULTURA",
    label: "ESCUELA NACIONAL CENTRAL DE AGRICULTURA",
  },
  {
    value: "FEDERACIÓN NACIONAL DE AJEDREZ DE GUATEMALA",
    label: "FEDERACIÓN NACIONAL DE AJEDREZ DE GUATEMALA",
  },
  {
    value: "INSTITUTO DE LA DEFENSA PÚBLICA PENAL",
    label: "INSTITUTO DE LA DEFENSA PÚBLICA PENAL",
  },
  {
    value: "INSTITUTO GUATEMALTECO DE TURISMO",
    label: "INSTITUTO GUATEMALTECO DE TURISMO",
  },
  {
    value: "INSTITUTO NACIONAL DE ADMINISTRACIÓN PÚBLICA",
    label: "INSTITUTO NACIONAL DE ADMINISTRACIÓN PÚBLICA",
  },
  {
    value: "INSTITUTO NACIONAL DE BOSQUES",
    label: "INSTITUTO NACIONAL DE BOSQUES",
  },
  {
    value: "INSTITUTO TÉCNICO DE CAPACITACIÓN Y PRODUCTIVIDAD",
    label: "INSTITUTO TÉCNICO DE CAPACITACIÓN Y PRODUCTIVIDAD",
  },
  {
    value: "MANCOMUNIDAD DE MUNICIPIOS DEL CONO SUR JUTIAPA",
    label: "MANCOMUNIDAD DE MUNICIPIOS DEL CONO SUR JUTIAPA",
  },
  {
    value: "MINISTERIO DE SALUD PÚBLICA Y ASISTENCIA SOCIAL",
    label: "MINISTERIO DE SALUD PÚBLICA Y ASISTENCIA SOCIAL",
  },
  { value: "MINISTERIO DE EDUCACIÓN", label: "MINISTERIO DE EDUCACIÓN" },
  { value: "MINISTERIO DE GOBERNACIÓN", label: "MINISTERIO DE GOBERNACIÓN" },
  { value: "MUNICIPALIDAD DE GUATEMALA", label: "MUNICIPALIDAD DE GUATEMALA" },
  {
    value: "PROCURADURÍA DE LOS DERECHOS HUMANOS",
    label: "PROCURADURÍA DE LOS DERECHOS HUMANOS",
  },
  {
    value: "REGISTRO GENERAL DE LA PROPIEDAD",
    label: "REGISTRO GENERAL DE LA PROPIEDAD",
  },
  {
    value: "REGISTRO NACIONAL DE LAS PERSONAS",
    label: "REGISTRO NACIONAL DE LAS PERSONAS",
  },
  {
    value: "SUPERINTENDENCIA DE ADMINISTRACIÓN TRIBUTARIA",
    label: "SUPERINTENDENCIA DE ADMINISTRACIÓN TRIBUTARIA",
  },
  { value: "TRIBUNAL SUPREMO ELECTORAL", label: "TRIBUNAL SUPREMO ELECTORAL" },
  {
    value: "UNIVERSIDAD DE SAN CARLOS DE GUATEMALA",
    label: "UNIVERSIDAD DE SAN CARLOS DE GUATEMALA",
  },
  {
    value: "INSTITUTO GUATEMALTECO DE SEGURIDAD SOCIAL",
    label: "INSTITUTO GUATEMALTECO DE SEGURIDAD SOCIAL",
  },
]

// =======================
// #region Anexo 6 – DEPENDENCIA - Ubicación administrativa (visible solo si INSTITUCIÓN = CGC)
// =======================
export type DependenciaValue =
  | "NO APLICA"
  | "DESPACHO GENERAL"
  | "SUBCONTRALORÍA DE PROBIDAD"
  | "SUBCONTRALORÍA DE CALIDAD DE GASTO PÚBLICO"
  | "SUBCONTRALORÍA ADMINISTRATIVA"
  | "INSPECCIÓN GENERAL"
  | "SECRETARÍA GENERAL"
  | "DIRECCIÓN DE AUDITORÍA INTERNA"
  | "DIRECCIÓN DE ASUNTOS JURÍDICOS"
  | "DIRECCIÓN DE SEGURIDAD INTEGRAL"
  | "DIRECCIÓN TÉCNICA SECTORIAL DE AUDITORÍA"
  | "DIRECCIÓN DE COMUNICACIÓN"
  | "DIRECCIÓN DE PROBIDAD"
  | "DIRECCIÓN DE CONTROL Y VERIFICACIÓN INTERINSTITUCIONAL"
  | "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR SALUD Y SEGURIDAD SOCIAL"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR DEFENSA, SEGURIDAD Y JUSTICIA"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR COMUNICACIONES, INFRAESTRUCTURA PÚBLICA Y VIVIENDA"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR MUNICIPALIDADES Y CONSEJOS DE DESARROLLO"
  | "DIRECCIÓN DE AUDITORÍA AL SECTOR ORGANISMOS E INSTITUCIONES DE APOYO"
  | "DIRECCIÓN DE AUDITORÍA A FIDEICOMISOS"
  | "DIRECCIÓN DE AUDITORÍA A OBRA PÚBLICA Y GESTIÓN AMBIENTAL"
  | "DIRECCIÓN DE AUDITORÍA A SISTEMAS INFORMÁTICOS Y NÓMINAS DE GOBIERNO"
  | "DIRECCIÓN DE AUDITORÍA PARA ATENCIÓN A DENUNCIAS"
  | "DIRECCIÓN DE ASEGURAMIENTO DE LA CALIDAD DE AUDITORÍA"
  | "DIRECCIÓN DE ANÁLISIS DE LA GESTIÓN PÚBLICA, MONITOREO Y ALERTA TEMPRANA"
  | "DIRECCIÓN DE CONTRA REVISIONES"
  | "DIRECCIÓN DE AUDITORÍA A RECURSOS PÚBLICOS DESTINADOS A PUEBLOS INDÍGENAS Y PUEBLOS VULNERABLES"
  | "DIRECCIÓN ADMINISTRATIVA"
  | "DIRECCIÓN FINANCIERA"
  | "DIRECCIÓN DE RECURSOS HUMANOS"
  | "DIRECCIÓN DE PLANIFICACIÓN"
  | "DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN"
  | "DIRECCIÓN DE FORMACIÓN Y CAPACITACIÓN EN FISCALIZACIÓN Y DE CONTROL GUBERNAMENTAL"
  | "DIRECCIÓN DE COOPERACIÓN Y RELACIONES INTERINSTITUCIONALES"
  | "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES (DUPLICADA)"
  | "DIRECCIÓN DE FORTALECIMIENTO AL CONTROL INTERNO Y DE GESTIÓN DE LAS UNIDADES DE AUDITORÍA INTERNA"
  | "DIRECCIÓN DE AUDITORÍA DE DESEMPEÑO"

export const DEPENDENCIA_OPTIONS: Option<DependenciaValue>[] = [
  { value: "NO APLICA", label: "NO APLICA" },
  { value: "DESPACHO GENERAL", label: "DESPACHO GENERAL" },
  { value: "SUBCONTRALORÍA DE PROBIDAD", label: "SUBCONTRALORÍA DE PROBIDAD" },
  {
    value: "SUBCONTRALORÍA DE CALIDAD DE GASTO PÚBLICO",
    label: "SUBCONTRALORÍA DE CALIDAD DE GASTO PÚBLICO",
  },
  {
    value: "SUBCONTRALORÍA ADMINISTRATIVA",
    label: "SUBCONTRALORÍA ADMINISTRATIVA",
  },
  { value: "INSPECCIÓN GENERAL", label: "INSPECCIÓN GENERAL" },
  { value: "SECRETARÍA GENERAL", label: "SECRETARÍA GENERAL" },
  {
    value: "DIRECCIÓN DE AUDITORÍA INTERNA",
    label: "DIRECCIÓN DE AUDITORÍA INTERNA",
  },
  {
    value: "DIRECCIÓN DE ASUNTOS JURÍDICOS",
    label: "DIRECCIÓN DE ASUNTOS JURÍDICOS",
  },
  {
    value: "DIRECCIÓN DE SEGURIDAD INTEGRAL",
    label: "DIRECCIÓN DE SEGURIDAD INTEGRAL",
  },
  {
    value: "DIRECCIÓN TÉCNICA SECTORIAL DE AUDITORÍA",
    label: "DIRECCIÓN TÉCNICA SECTORIAL DE AUDITORÍA",
  },
  { value: "DIRECCIÓN DE COMUNICACIÓN", label: "DIRECCIÓN DE COMUNICACIÓN" },
  { value: "DIRECCIÓN DE PROBIDAD", label: "DIRECCIÓN DE PROBIDAD" },
  {
    value: "DIRECCIÓN DE CONTROL Y VERIFICACIÓN INTERINSTITUCIONAL",
    label: "DIRECCIÓN DE CONTROL Y VERIFICACIÓN INTERINSTITUCIONAL",
  },
  {
    value: "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES",
    label: "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA AL SECTOR SALUD Y SEGURIDAD SOCIAL",
    label: "DIRECCIÓN DE AUDITORÍA AL SECTOR SALUD Y SEGURIDAD SOCIAL",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR EDUCACIÓN, CIENCIA, CULTURA Y DEPORTES",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA AL SECTOR DEFENSA, SEGURIDAD Y JUSTICIA",
    label: "DIRECCIÓN DE AUDITORÍA AL SECTOR DEFENSA, SEGURIDAD Y JUSTICIA",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR MEDIO AMBIENTE Y RECURSOS NATURALES",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR ECONOMÍA, FINANZAS, TRABAJO Y PREVISIÓN SOCIAL",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR COMUNICACIONES, INFRAESTRUCTURA PÚBLICA Y VIVIENDA",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR COMUNICACIONES, INFRAESTRUCTURA PÚBLICA Y VIVIENDA",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR MUNICIPALIDADES Y CONSEJOS DE DESARROLLO",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR MUNICIPALIDADES Y CONSEJOS DE DESARROLLO",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR ORGANISMOS E INSTITUCIONES DE APOYO",
    label:
      "DIRECCIÓN DE AUDITORÍA AL SECTOR ORGANISMOS E INSTITUCIONES DE APOYO",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA A FIDEICOMISOS",
    label: "DIRECCIÓN DE AUDITORÍA A FIDEICOMISOS",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA A OBRA PÚBLICA Y GESTIÓN AMBIENTAL",
    label: "DIRECCIÓN DE AUDITORÍA A OBRA PÚBLICA Y GESTIÓN AMBIENTAL",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA A SISTEMAS INFORMÁTICOS Y NÓMINAS DE GOBIERNO",
    label:
      "DIRECCIÓN DE AUDITORÍA A SISTEMAS INFORMÁTICOS Y NÓMINAS DE GOBIERNO",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA PARA ATENCIÓN A DENUNCIAS",
    label: "DIRECCIÓN DE AUDITORÍA PARA ATENCIÓN A DENUNCIAS",
  },
  {
    value: "DIRECCIÓN DE ASEGURAMIENTO DE LA CALIDAD DE AUDITORÍA",
    label: "DIRECCIÓN DE ASEGURAMIENTO DE LA CALIDAD DE AUDITORÍA",
  },
  {
    value:
      "DIRECCIÓN DE ANÁLISIS DE LA GESTIÓN PÚBLICA, MONITOREO Y ALERTA TEMPRANA",
    label:
      "DIRECCIÓN DE ANÁLISIS DE LA GESTIÓN PÚBLICA, MONITOREO Y ALERTA TEMPRANA",
  },
  {
    value: "DIRECCIÓN DE CONTRA REVISIONES",
    label: "DIRECCIÓN DE CONTRA REVISIONES",
  },
  {
    value:
      "DIRECCIÓN DE AUDITORÍA A RECURSOS PÚBLICOS DESTINADOS A PUEBLOS INDÍGENAS Y PUEBLOS VULNERABLES",
    label:
      "DIRECCIÓN DE AUDITORÍA A RECURSOS PÚBLICOS DESTINADOS A PUEBLOS INDÍGENAS Y PUEBLOS VULNERABLES",
  },
  { value: "DIRECCIÓN ADMINISTRATIVA", label: "DIRECCIÓN ADMINISTRATIVA" },
  { value: "DIRECCIÓN FINANCIERA", label: "DIRECCIÓN FINANCIERA" },
  {
    value: "DIRECCIÓN DE RECURSOS HUMANOS",
    label: "DIRECCIÓN DE RECURSOS HUMANOS",
  },
  { value: "DIRECCIÓN DE PLANIFICACIÓN", label: "DIRECCIÓN DE PLANIFICACIÓN" },
  {
    value: "DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN",
    label: "DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN",
  },
  {
    value:
      "DIRECCIÓN DE FORMACIÓN Y CAPACITACIÓN EN FISCALIZACIÓN Y DE CONTROL GUBERNAMENTAL",
    label:
      "DIRECCIÓN DE FORMACIÓN Y CAPACITACIÓN EN FISCALIZACIÓN Y DE CONTROL GUBERNAMENTAL",
  },
  {
    value: "DIRECCIÓN DE COOPERACIÓN Y RELACIONES INTERINSTITUCIONALES",
    label: "DIRECCIÓN DE COOPERACIÓN Y RELACIONES INTERINSTITUCIONALES",
  },
  {
    value: "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES (DUPLICADA)",
    label: "DIRECCIÓN DE DELEGACIONES DEPARTAMENTALES (DUPLICADA)",
  },
  {
    value:
      "DIRECCIÓN DE FORTALECIMIENTO AL CONTROL INTERNO Y DE GESTIÓN DE LAS UNIDADES DE AUDITORÍA INTERNA",
    label:
      "DIRECCIÓN DE FORTALECIMIENTO AL CONTROL INTERNO Y DE GESTIÓN DE LAS UNIDADES DE AUDITORÍA INTERNA",
  },
  {
    value: "DIRECCIÓN DE AUDITORÍA DE DESEMPEÑO",
    label: "DIRECCIÓN DE AUDITORÍA DE DESEMPEÑO",
  },
]

// =======================
// #region Anexo 7 – Renglón presupuestario
// =======================
export type RenglonValue =
  | "PERSONAL PERMANENTE 011"
  | "GRUPO 029"
  | "SUBGRUPO 18 Y 022"
  | "NO APLICA"
  | "RENGLÓN 021"

export const RENGLON_OPTIONS: Option<RenglonValue>[] = [
  { value: "PERSONAL PERMANENTE 011", label: "PERSONAL PERMANENTE 011" },
  { value: "GRUPO 029", label: "GRUPO 029" },
  { value: "SUBGRUPO 18 Y 022", label: "SUBGRUPO 18 Y 022" },
  { value: "NO APLICA", label: "NO APLICA" },
  { value: "RENGLÓN 021", label: "RENGLÓN 021" },
]

// =======================
// #region Anexo 8 – Colegios profesionales
// =======================
export type ColegioValue =
  | "NO APLICA"
  | "COLEGIO PROFESIONAL DE HUMANIDADES DE GUATEMALA"
  | "COLEGIO DE ARQUITECTOS DE GUATEMALA"
  | "COLEGIO DE CONTADORES PUBLICOS Y AUDITORES DE GUATEMALA"
  | "COLEGIO DE ECONOMISTAS, CONTADORES PUBLICOS Y AUDITORES Y ADMINISTRADORES DE EMPRESAS"
  | "COLEGIO DE FARMACEUTICOS Y QUIMICOS DE GUATEMALA"
  | "COLEGIO DE INGENIEROS AGRONOMOS DE GUATEMALA"
  | "COLEGIO DE INGENIEROS DE GUATEMALA"
  | "COLEGIO DE INGENIEROS QUIMICOS DE GUATEMALA"
  | "COLEGIO DE MEDICOS VETERINARIOS Y ZOOTECNISTAS DE GUATEMALA"
  | "COLEGIO DE MEDICOS Y CIRUJANOS DE GUATEMALA"
  | "COLEGIO DE PSICOLOGOS DE GUATEMALA"
  | "COLEGIO ESTOMATOLOGICO DE GUATEMALA"
  | "COLEGIO DE ABOGADOS Y NOTARIOS DE GUATEMALA"
  | "COLEGIO PROFESIONAL DE ENFERMERIA DE GUATEMALA"

export const COLEGIO_OPTIONS: Option<ColegioValue>[] = [
  { value: "NO APLICA", label: "NO APLICA" },
  {
    value: "COLEGIO PROFESIONAL DE HUMANIDADES DE GUATEMALA",
    label: "COLEGIO PROFESIONAL DE HUMANIDADES DE GUATEMALA",
  },
  {
    value: "COLEGIO DE ARQUITECTOS DE GUATEMALA",
    label: "COLEGIO DE ARQUITECTOS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE CONTADORES PUBLICOS Y AUDITORES DE GUATEMALA",
    label: "COLEGIO DE CONTADORES PUBLICOS Y AUDITORES DE GUATEMALA",
  },
  {
    value:
      "COLEGIO DE ECONOMISTAS, CONTADORES PUBLICOS Y AUDITORES Y ADMINISTRADORES DE EMPRESAS",
    label:
      "COLEGIO DE ECONOMISTAS, CONTADORES PUBLICOS Y AUDITORES Y ADMINISTRADORES DE EMPRESAS",
  },
  {
    value: "COLEGIO DE FARMACEUTICOS Y QUIMICOS DE GUATEMALA",
    label: "COLEGIO DE FARMACEUTICOS Y QUIMICOS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE INGENIEROS AGRONOMOS DE GUATEMALA",
    label: "COLEGIO DE INGENIEROS AGRONOMOS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE INGENIEROS DE GUATEMALA",
    label: "COLEGIO DE INGENIEROS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE INGENIEROS QUIMICOS DE GUATEMALA",
    label: "COLEGIO DE INGENIEROS QUIMICOS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE MEDICOS VETERINARIOS Y ZOOTECNISTAS DE GUATEMALA",
    label: "COLEGIO DE MEDICOS VETERINARIOS Y ZOOTECNISTAS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE MEDICOS Y CIRUJANOS DE GUATEMALA",
    label: "COLEGIO DE MEDICOS Y CIRUJANOS DE GUATEMALA",
  },
  {
    value: "COLEGIO DE PSICOLOGOS DE GUATEMALA",
    label: "COLEGIO DE PSICOLOGOS DE GUATEMALA",
  },
  {
    value: "COLEGIO ESTOMATOLOGICO DE GUATEMALA",
    label: "COLEGIO ESTOMATOLOGICO DE GUATEMALA",
  },
  {
    value: "COLEGIO DE ABOGADOS Y NOTARIOS DE GUATEMALA",
    label: "COLEGIO DE ABOGADOS Y NOTARIOS DE GUATEMALA",
  },
  {
    value: "COLEGIO PROFESIONAL DE ENFERMERIA DE GUATEMALA",
    label: "COLEGIO PROFESIONAL DE ENFERMERIA DE GUATEMALA",
  },
]

// =============== Helpers opcionales ===============
// Derivar el tipo literal desde las opciones, si prefieres:
// export type SectorValue = typeof SECTOR_OPTIONS[number]["value"]
